### ISSUE TITLE
Add Read List of Files From File

### ISSUE THREAD

**Issue by ossie-git** [boyter/hashit#8]
Hi, 

It would be great if support for this can be added. Thanks

**Comment by boyter** [comment]
Not sure what you mean here. What is missing? The default output includes the list of the file, for example 

```
$ hashit processor 
processor/processor.go (4841 bytes)
        MD5 37ac7ccccd27602c855a60e4833bc399
       SHA1 95920992bb432467c66d14d500f42dbede9eba18
     SHA256 90bc33a8c4c7a6c5e0d358bb7b9db3bcc6cdf5feb8748ab8d10eb5a123b3c6dc
     SHA512 dbbfc97729d72fbd01026f28d860cdff261105b5ab4ce1f17c740dc559483fe1b575c494191794a9f08d42ba5fb98214fd93ae2e7045f661ad02640158416a7a

processor/file.go (412 bytes)
        MD5 fea2253b11e12a134efebee40c7ca544
       SHA1 2eda7b80cfc7aac9a5d5648da3a8a4f2231e00d2
     SHA256 d6d0410c9fd662f08ccf2586661ff3c9623c68d209dec680ac8553ae5ebcf899
     SHA512 ecffcc685a94858f034a708fed115bee43d8348071f19530617104d7bc195cfbbb916683b9b5cf1441a036c91d0413bae94592193baaae689d38205f87e04542
```

Which has every file it read, which should be every file that it walked.

**Comment by ossie-git** [comment]
Perhaps I should have worded it better. By default, it can hash a file or directory. What if I want something more complex and only want it to hash executables? Or images? Or to ignore certain files? Currently, as far as I can see, there is no option to do so and you would have to write a script to do this, which would also mean that you lose the ability to use multiple CPU cores as your script would invoke an instance per file. By allowing reading from a file, one can use something like [fd](https://github.com/sharkdp/fd) to select the files and pipe this to a file (or directly if you allow reading from stdin) and then have **hashit** read from this file

**Comment by boyter** [comment]
The ability to use multiple CPU's remains in the above case actually because hashit will process each hash on a different thread. By default this caps out at 4 threads due to there being the default 4 hashes, so not the total disaster you might expect.

That said having the ability to supply an input file seems like a legitimate use case.

**Comment by boyter** [comment]
Had a spare moment, so added it in.

```
$ hashit -i inputfile.txt
/Users/boyter/Documents/projects/hashit/main.go (2280 bytes)
        MD5 1baa60530964bdefe02b326c595d09da
       SHA1 5bb404cea2a87fe3198a370bdf05a665910cfb81
     SHA256 bd387c7c9ccebba43c45ac70e005132b3b2995396ef21605180200b8012e8a3a
     SHA512 0a438e46e4150bffe2ac855006835c81911e432ea8dfc3275b00fbb82c9bdbb1e66fd15596386ae7c6a8b7c2afaae896444557dab8975320f1b0b788f64080bf

/Users/boyter/Documents/projects/hashit/LICENSE (1067 bytes)
        MD5 227f999ca03b135a1b4d69bde84afb16
       SHA1 2c7beb1563981414f31481016816a88dc0cdba16
     SHA256 fb3f44f5e74b957107f89b027896250ecff74718b1fa8bf0566874e142e54351
     SHA512 882eb7ee56cda80778dbd44f514e68a14126a61a11a825f9c030a3425b941d6a3636561a466347178d8bf204dbedc806471d248637091b311ca37ec18a1c084b

/Users/boyter/Documents/projects/hashit/README.md (8964 bytes)
        MD5 22ed507c2a5fc7b822c8080340d799ab
       SHA1 2e74fa58da1f19b66b5826cf73d0c28a6c48aed6
     SHA256 c84475732426797adfc3b1f14717d1aeeee976ca19ddd596f2ea5e59c932a062
     SHA512 4f77e1d43cfcdb04c1ad99b5d53087b960ea7301da21f76de42cfefe77eb6f0bb3d2781db6c99f3f99d161e76c68d5a74a990b81e4e908a7104aef7d512efd31

# boyter @ macbookair in ~/Documents/projects/hashit on git:master x [10:56:17] 
$ cat inputfile.txt 
/Users/boyter/Documents/projects/hashit/main.go
/Users/boyter/Documents/projects/hashit/LICENSE
/Users/boyter/Documents/projects/hashit/README.md%     
```

Supply the input file with the relative or full path to the file and it should work. You will need to build from master for this but ill cut a release sometime soon after I test it a bit more.

**Comment by ossie-git** [comment]
Cool. Thanks a lot. I tried using it but it looks like the build failed and the change didn't make it to the repo. I tried all of the following:

```
go install github.com/boyter/hashit@latest
go install github.com/boyter/hashit@adda928
```

as well as:

```
git clone --depth=1 https://github.com/boyter/hashit
```

and none of them had the `-i` option:

```
$ ./hashit -i
Error: flag needs an argument: 'i' in -i
```

**Comment by ossie-git** [comment]
Cool. Thanks a lot. Will try it out
